name: unity_md
description: UNITY-MD WhatsApp Bot Controller
publish_to: 'none'
version: 1.0.9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.2
  just_audio: ^0.9.36
  permission_handler: ^11.3.1
  open_filex: ^4.3.4
  package_info_plus: ^6.0.0
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
